nodePort:
image:
  #repository: data61/
  #tag: latest
  #full: terria-terrimap:1.0
  pullPolicy: Always
clientConfig:
  initializationUrls:
  - helm
  - terria
  parameters:
    bingMapsKey: AkaOmRFtjAb71cXgLwAGtLbj2RpkPKtVqAIroFQsocfurCBILxIeAWPkil7hhRy_
    disclaimer:
      text: "Disclaimer: This map must not be used for navigation or precise spatial analysis"
      url: "http://google.com"
    globalDisclaimer:
      confirmationRequired: true
      buttonTitle: "I agree"
      title: "Disclaimer"
      prodHostRegex: "gov.\\.au$"
      devHostRegex: "\\b(staging|preview|test|dev)\\."
      enableOnLocalhost: true
    developerAttribution:
      text: "Your organisation"
      link: "http://www.example.com"
    appName: "Terria Map"
    brandBarElements: ["", "<a target=\"_blank\" href=\"http://terria.io\"><img src=\"images/terria_logo.png\" height=\"52\" title=\"Version: {{version}}\" /></a>", ""]
    supportEmail: "help@example.com"
    mobileDefaultViewerMode: "2d"
    experimentalFeatures: true
initConfig:
  homeCamera:
    north: "-8"
    east: "158"
    south: "-45"
    west: "109"
  catalog: []
serverConfig:
  port: 3001
  allowProxyFor: []
  initPaths:
  - "/etc/config/client"
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
